aws:
  access_key: <%= ENV['AWS_ACCESS_KEY'] %>
  secret: <%= ENV['SECRET_ACCESS_KEY'] %>
  s3:
    endpoint: s3-ap-northeast-1.amazonaws.com
    bucket: dev-code4startup-image
webpay:
  public_key: test_public_fvh7UPd4AfvC6825vxf8oelQ
  access_key: test_secret_c6E5NG65v0t64FE0N132RbkC
  credential: hookcred_2gn3CpfaLbwNd4MfvF0D57w6fM60A8gdbgHy
